language: python

python:
  - '3.5'
  - '2.7'
  - '2.6'
  - '3.4'
  - '3.6'

matrix:
  include:
    - python: '3.7'
      dist: xenial  # required for Python >= 3.7 (travis-ci/travis-ci#9069)

install:
- pip install -e .
- pip install -r requirements-dev.txt

script:
- python ./setup.py develop && COMPILE='--compile' make check

# blacklist
branches:
  except:
    - data-driven-pytest
